import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

const apiBase = String.fromEnvironment('API_BASE', defaultValue: 'http://10.0.2.2:8000');

void main() => runApp(const PognaliApp());

class PognaliApp extends StatelessWidget {
  const PognaliApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'Погнали',
    theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.orange, scaffoldBackgroundColor: const Color(0xFFF8F7F4)),
    home: const HomeScreen(),
  );
}

class AuthRequired implements Exception {}

class UserModel {
  final int id; final String name, city, bio, photoUrl; final DateTime? birthDate;
  UserModel({required this.id, required this.name, required this.city, this.bio='', this.photoUrl='', this.birthDate});
  factory UserModel.fromJson(Map<String,dynamic> j)=>UserModel(id:j['id'],name:j['name']??'',city:j['city']??'',bio:j['bio']??'',photoUrl:j['photo_url']??'',birthDate:j['birth_date']==null?null:DateTime.tryParse(j['birth_date']));
  int? get age { if(birthDate==null)return null; final n=DateTime.now(); var a=n.year-birthDate!.year; if(DateTime(n.year,birthDate!.month,birthDate!.day).isAfter(n))a--; return a; }
}

class EventModel {
  final int id, people, capacity; final String title, place, time, description; final double lat,lon; final bool joined;
  final DateTime startsAt;
  EventModel({required this.id,required this.title,required this.place,required this.time,required this.people,required this.capacity,required this.startsAt,this.description='',this.lat=44.9521,this.lon=34.1024,this.joined=false});
  factory EventModel.fromJson(Map<String,dynamic> j){final d=DateTime.tryParse(j['starts_at'].toString())?.toLocal()??DateTime.now(); return EventModel(id:j['id'],title:j['title'],place:j['location'],time:'${d.day.toString().padLeft(2,'0')}.${d.month.toString().padLeft(2,'0')}  ${d.hour.toString().padLeft(2,'0')}:${d.minute.toString().padLeft(2,'0')}',startsAt:d,people:j['participants']??0,capacity:j['capacity']??10,description:j['description']??'',lat:(j['lat']??44.9521).toDouble(),lon:(j['lon']??34.1024).toDouble(),joined:j['is_joined']??false);}
}

class Api {
  static Future<String?> token() async => (await SharedPreferences.getInstance()).getString('token');
  static Future<void> saveToken(String t) async => (await SharedPreferences.getInstance()).setString('token',t);
  static Future<void> logout() async => (await SharedPreferences.getInstance()).remove('token');
  static Future<UserModel> devLogin({required String id, required String name}) async { final r=await http.post(Uri.parse('$apiBase/auth/dev'),headers:{'Content-Type':'application/json'},body:jsonEncode({'provider_user_id':id,'name':name})); if(r.statusCode!=200)throw Exception('Не удалось войти'); final j=jsonDecode(r.body); await saveToken(j['access_token']); return UserModel.fromJson(j['user']); }
  static Future<List<EventModel>> events() async { final t=await token(); final r=await http.get(Uri.parse('$apiBase/events'),headers:{if(t!=null)'Authorization':'Bearer $t'}); if(r.statusCode!=200)throw Exception('Не удалось загрузить события'); return (jsonDecode(r.body) as List).map((x)=>EventModel.fromJson(x)).toList(); }
  static Future<EventModel> event(int id) async { final t=await token(); final r=await http.get(Uri.parse('$apiBase/events/$id'),headers:{if(t!=null)'Authorization':'Bearer $t'}); if(r.statusCode!=200)throw Exception('Событие не найдено'); return EventModel.fromJson(jsonDecode(r.body)); }
  static Future<List<UserModel>> participants(int id) async { final r=await http.get(Uri.parse('$apiBase/events/$id/participants')); if(r.statusCode!=200)throw Exception('Не удалось загрузить участников'); return (jsonDecode(r.body) as List).map((x)=>UserModel.fromJson(x)).toList(); }
  static Future<List<dynamic>> messages(int id) async { final t=await token(); if(t==null)throw AuthRequired(); final r=await http.get(Uri.parse('$apiBase/events/$id/messages'),headers:{'Authorization':'Bearer $t'}); if(r.statusCode==401)throw AuthRequired(); if(r.statusCode!=200)throw Exception('Не удалось загрузить чат'); return jsonDecode(r.body) as List; }
  static Future<void> sendMessage(int id,String text) async { final t=await token(); if(t==null)throw AuthRequired(); final r=await http.post(Uri.parse('$apiBase/events/$id/messages'),headers:{'Authorization':'Bearer $t','Content-Type':'application/json'},body:jsonEncode({'text':text})); if(r.statusCode==401)throw AuthRequired(); if(r.statusCode!=200)throw Exception('Не удалось отправить сообщение'); }
  static Future<void> join(int id) async { final t=await token(); if(t==null)throw AuthRequired(); final r=await http.post(Uri.parse('$apiBase/events/$id/join'),headers:{'Authorization':'Bearer $t'}); if(r.statusCode==401)throw AuthRequired(); if(r.statusCode!=200)throw Exception((jsonDecode(r.body)['detail']??'Не удалось присоединиться').toString()); }
  static Future<void> leave(int id) async { final t=await token(); if(t==null)throw AuthRequired(); final r=await http.post(Uri.parse('$apiBase/events/$id/leave'),headers:{'Authorization':'Bearer $t'}); if(r.statusCode==401)throw AuthRequired(); if(r.statusCode!=200)throw Exception('Не удалось выйти'); }
  static Future<UserModel> me() async { final t=await token(); if(t==null)throw AuthRequired(); final r=await http.get(Uri.parse('$apiBase/me'),headers:{'Authorization':'Bearer $t'}); if(r.statusCode==401)throw AuthRequired(); return UserModel.fromJson(jsonDecode(r.body)); }
  static Future<UserModel> updateMe({String? name,String? city,DateTime? birthDate,String? bio,String? photoUrl}) async { final t=await token(); if(t==null)throw AuthRequired(); final b=<String,dynamic>{}; if(name!=null)b['name']=name;if(city!=null)b['city']=city;if(birthDate!=null)b['birth_date']=birthDate.toIso8601String().substring(0,10);if(bio!=null)b['bio']=bio;if(photoUrl!=null)b['photo_url']=photoUrl; final r=await http.patch(Uri.parse('$apiBase/me'),headers:{'Authorization':'Bearer $t','Content-Type':'application/json'},body:jsonEncode(b));if(r.statusCode==401)throw AuthRequired();return UserModel.fromJson(jsonDecode(r.body)); }
  static Future<void> createEvent({required String title,required String location,required DateTime startsAt,required int capacity,String description=''}) async { final t=await token();if(t==null)throw AuthRequired();final r=await http.post(Uri.parse('$apiBase/events'),headers:{'Authorization':'Bearer $t','Content-Type':'application/json'},body:jsonEncode({'title':title,'city':'Симферополь','location':location,'starts_at':startsAt.toUtc().toIso8601String(),'capacity':capacity,'description':description,'lat':44.9521,'lon':34.1024}));if(r.statusCode==401)throw AuthRequired();if(r.statusCode!=200)throw Exception((jsonDecode(r.body)['detail']??'Не удалось создать событие').toString()); }
}

class HomeScreen extends StatefulWidget{const HomeScreen({super.key});@override State<HomeScreen> createState()=>_HomeScreenState();}
class _HomeScreenState extends State<HomeScreen>{
  int tab=0; bool mapMode=true,loading=true; String filter='Сегодня'; List<EventModel> all=[];
  @override void initState(){super.initState();_load();}
  Future<void> _load()async{try{final e=await Api.events();if(mounted)setState(()=>all=e);}catch(_){ }finally{if(mounted)setState(()=>loading=false);}}
  List<EventModel> get filtered { final now=DateTime.now(); DateTime day(int n)=>DateTime(now.year,now.month,now.day+n); return all.where((e){final d=e.startsAt; if(filter=='Сейчас')return d.isAfter(now.subtract(const Duration(hours:1)))&&d.isBefore(now.add(const Duration(hours:3)));if(filter=='Сегодня')return d.year==now.year&&d.month==now.month&&d.day==now.day;if(filter=='Завтра'){final x=day(1);return d.year==x.year&&d.month==x.month&&d.day==x.day;}if(filter=='Выходные'){final wd=now.weekday;final sat=now.add(Duration(days:(6-wd)));final sun=sat.add(const Duration(days:1));final a=DateTime(sat.year,sat.month,sat.day),b=DateTime(sun.year,sun.month,sun.day+1);return !d.isBefore(a)&&d.isBefore(b);}return true;}).toList(); }
  @override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,12,16,8),child:Row(children:[Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Погнали',style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w900)),FutureBuilder<String?>(future:Api.token(),builder:(_,snap)=>Text(snap.data==null?'Смотри, выбирай, иди.':'Ты в системе',style:Theme.of(c).textTheme.bodySmall?.copyWith(color:Colors.grey[700]))) ]),const Spacer(),IconButton(onPressed:()=>setState(()=>mapMode=!mapMode),icon:Icon(mapMode?Icons.view_list:Icons.map_outlined))])),SizedBox(height:42,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:12),children:[for(final x in ['Сейчас','Сегодня','Завтра','Выходные','Все'])Padding(padding:const EdgeInsets.symmetric(horizontal:4),child:ChoiceChip(label:Text(x),selected:filter==x,onSelected:(_){setState(()=>filter=x);})),])),const SizedBox(height:6),Expanded(child:loading?const Center(child:CircularProgressIndicator()):filtered.isEmpty?Center(child:Padding(padding:const EdgeInsets.all(32),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.explore_outlined,size:56),const SizedBox(height:12),Text('Пока здесь пусто',style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:6),const Text('Создай событие первым — или выбери другой день.'),const SizedBox(height:14),FilledButton.icon(onPressed:_create,icon:const Icon(Icons.add),label:const Text('Создать событие'))]))):mapMode?_map(filtered):_list(filtered)])),floatingActionButton:FloatingActionButton.extended(onPressed:_create,icon:const Icon(Icons.add),label:const Text('Создать')),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)async{if(i==1){await _create();}else if(i==2){await Navigator.push(c,MaterialPageRoute(builder:(_)=>const ProfileScreen()));if(mounted)setState(()=>tab=0);}else setState(()=>tab=0);},destinations:const[NavigationDestination(icon:Icon(Icons.map),label:'Карта'),NavigationDestination(icon:Icon(Icons.add_circle_outline),label:'Создать'),NavigationDestination(icon:Icon(Icons.person_outline),label:'Профиль')]));
  Widget _map(List<EventModel> es)=>FlutterMap(options:const MapOptions(initialCenter:LatLng(44.9521,34.1024),initialZoom:13),children:[TileLayer(urlTemplate:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',userAgentPackageName:'ru.pognali.app'),MarkerLayer(markers:[for(final e in es)Marker(point:LatLng(e.lat,e.lon),width:62,height:62,child:GestureDetector(onTap:()=>_open(e),child:Container(decoration:BoxDecoration(color:Theme.of(context).colorScheme.primary,shape:BoxShape.circle,border:Border.all(color:Colors.white,width:3)),child:Center(child:Text('${e.people}/${e.capacity}',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.bold))))))])]);
  Widget _list(List<EventModel> es)=>ListView.builder(padding:const EdgeInsets.all(12),itemCount:es.length,itemBuilder:(_,i)=>_card(es[i]));
  Widget _card(EventModel e)=>Card(child:InkWell(onTap:()=>_open(e),borderRadius:BorderRadius.circular(14),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(e.title,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w700)),const SizedBox(height:8),Text('🕒 ${e.time}'),Text('📍 ${e.place}'),Text('👥 ${e.people}/${e.capacity}'),const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton(onPressed:e.people>=e.capacity&&!e.joined?null:()=>_open(e),child:Text(e.joined?'Я ИДУ':e.people>=e.capacity?'МЕСТ НЕТ':'ПОЙДУ')))]))));
  Future<void> _open(EventModel e)async{final fresh=await Api.event(e.id);if(!mounted)return;await showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(_)=>EventSheet(event:fresh,onChanged:(){Navigator.pop(context);_load();}));}
  Future<void> _join(EventModel e)async{try{await Api.join(e.id);if(mounted){Navigator.pop(context);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Ты участник. Погнали!')));_load();}}catch(x){if(x is AuthRequired)_needAuth('пойти на событие');else if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x.toString())));}}
  Future<void> _create()async{if(await Api.token()==null){_needAuth('создать событие');return;}final t=TextEditingController(),l=TextEditingController(),d=TextEditingController();int cap=10;DateTime starts=DateTime.now().add(const Duration(hours:2));await showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(ctx)=>StatefulBuilder(builder:(ctx,set)=>Padding(padding:EdgeInsets.fromLTRB(20,8,20,20+MediaQuery.of(ctx).viewInsets.bottom),child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Новое событие',style:Theme.of(ctx).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:16),TextField(controller:t,decoration:const InputDecoration(labelText:'Что делаем?',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:l,decoration:const InputDecoration(labelText:'Где?',border:OutlineInputBorder())),const SizedBox(height:10),ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.schedule),title:Text('${starts.day.toString().padLeft(2,'0')}.${starts.month.toString().padLeft(2,'0')}  ${starts.hour.toString().padLeft(2,'0')}:${starts.minute.toString().padLeft(2,'0')}'),onTap:()async{final date=await showDatePicker(context:ctx,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:365)),initialDate:starts);if(date==null)return;final time=await showTimePicker(context:ctx,initialTime:TimeOfDay.fromDateTime(starts));if(time!=null)set(()=>starts=DateTime(date.year,date.month,date.day,time.hour,time.minute));}),Row(children:[const Text('Участников: '),IconButton(onPressed:cap>2?()=>set(()=>cap--):null,icon:const Icon(Icons.remove_circle_outline)),Text('$cap',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),IconButton(onPressed:cap<100?()=>set(()=>cap++):null,icon:const Icon(Icons.add_circle_outline))]),TextField(controller:d,maxLines:3,decoration:const InputDecoration(labelText:'Описание (необязательно)',border:OutlineInputBorder())),const SizedBox(height:14),SizedBox(width:double.infinity,child:FilledButton(onPressed:()async{if(t.text.trim().isEmpty||l.text.trim().isEmpty){ScaffoldMessenger.of(ctx).showSnackBar(const SnackBar(content:Text('Заполни, что и где')));return;}try{await Api.createEvent(title:t.text.trim(),location:l.text.trim(),startsAt:starts,capacity:cap,description:d.text.trim());if(ctx.mounted)Navigator.pop(ctx);await _load();}catch(e){if(ctx.mounted)ScaffoldMessenger.of(ctx).showSnackBar(SnackBar(content:Text(e.toString())));}},child:const Text('ПОГНАЛИ')))]))));}
  void _needAuth(String action){
    showModalBottomSheet(context:context,showDragHandle:true,builder:(sheet)=>Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[
      Text('Чтобы $action',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),
      const SizedBox(height:8),
      const Text('Смотреть события можно без регистрации. Для участия нужен аккаунт.'),
      const SizedBox(height:18),
      SizedBox(width:double.infinity,child:FilledButton(onPressed:()async{try{await Api.devLogin(id:'demo_user',name:'Новый пользователь');if(sheet.mounted)Navigator.pop(sheet);if(mounted)setState((){});}catch(e){if(sheet.mounted)ScaffoldMessenger.of(sheet).showSnackBar(SnackBar(content:Text(e.toString())));}},child:const Text('Продолжить как новый пользователь'))),
      const SizedBox(height:8),
      SizedBox(width:double.infinity,child:OutlinedButton(onPressed:()async{try{await Api.devLogin(id:'demo_stas',name:'Стас');if(sheet.mounted)Navigator.pop(sheet);if(mounted)setState((){});}catch(e){if(sheet.mounted)ScaffoldMessenger.of(sheet).showSnackBar(SnackBar(content:Text(e.toString())));}},child:const Text('Тестовый вход: Стас'))),
      const SizedBox(height:8),
      const Center(child:Text('Google / ВКонтакте подключим после настройки OAuth.',style:TextStyle(fontSize:12,color:Colors.grey))),
    ]));
  }

}

class EventSheet extends StatefulWidget{final EventModel event;final VoidCallback onChanged;const EventSheet({super.key,required this.event,required this.onChanged});@override State<EventSheet> createState()=>_EventSheetState();}
class _EventSheetState extends State<EventSheet>{late EventModel e;List<UserModel> users=[];List<dynamic> messages=[];final msg=TextEditingController();bool busy=false;@override void initState(){super.initState();e=widget.event;_load();}Future<void> _load()async{try{final u=await Api.participants(e.id);if(mounted)setState(()=>users=u);}catch(_){}if(e.joined){try{final m=await Api.messages(e.id);if(mounted)setState(()=>messages=m);}catch(_) {}}}Future<void> _join()async{try{setState(()=>busy=true);await Api.join(e.id);final x=await Api.event(e.id);if(mounted)setState(()=>e=x);await _load();}catch(x){if(x is AuthRequired){Navigator.pop(context);widget.onChanged();return;}if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x.toString())));}finally{if(mounted)setState(()=>busy=false);}}Future<void> _leave()async{try{setState(()=>busy=true);await Api.leave(e.id);final x=await Api.event(e.id);if(mounted)setState(()=>e=x);messages=[];}catch(x){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x.toString())));}finally{if(mounted)setState(()=>busy=false);}}Future<void> _send()async{final text=msg.text.trim();if(text.isEmpty)return;try{await Api.sendMessage(e.id,text);msg.clear();final m=await Api.messages(e.id);if(mounted)setState(()=>messages=m);}catch(x){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x.toString())));}}@override Widget build(BuildContext c)=>Padding(padding:EdgeInsets.fromLTRB(20,4,20,20+MediaQuery.of(c).viewInsets.bottom),child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(e.title,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:10),Text('🕒 ${e.time}'),Text('📍 ${e.place}'),Text('👥 ${e.people}/${e.capacity}'),if(e.description.isNotEmpty)...[const SizedBox(height:12),Text(e.description)],const SizedBox(height:16),Text('Участники',style:Theme.of(c).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:8),Wrap(spacing:8,runSpacing:8,children:[for(final u in users)Chip(avatar:u.photoUrl.isEmpty?const Icon(Icons.person,size:18):CircleAvatar(backgroundImage:NetworkImage(u.photoUrl)),label:Text(u.name))]),const SizedBox(height:16),if(e.joined)...[Row(children:[Expanded(child:OutlinedButton(onPressed:busy?null:_leave,child:const Text('ВЫЙТИ'))),const SizedBox(width:8),Expanded(child:FilledButton(onPressed:()=>_chat(context),child:const Text('ЧАТ')))] )]else SizedBox(width:double.infinity,child:FilledButton(onPressed:(e.people>=e.capacity||busy)?null:_join,child:Text(e.people>=e.capacity?'МЕСТ НЕТ':'ПОЙДУ')))])));
  Future<void> _chat(BuildContext c)async{await showModalBottomSheet(context:c,isScrollControlled:true,showDragHandle:true,builder:(_)=>Padding(padding:EdgeInsets.fromLTRB(16,8,16,16+MediaQuery.of(c).viewInsets.bottom),child:SizedBox(height:MediaQuery.of(c).size.height*0.72,child:Column(children:[Row(children:[Text('Чат события',style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const Spacer(),IconButton(onPressed:()=>Navigator.pop(c),icon:const Icon(Icons.close))]),Expanded(child:ListView(children:[for(final m in messages)ListTile(title:Text(m['text']??''),subtitle:Text(m['user_name']??''))])),Row(children:[Expanded(child:TextField(controller:msg,onSubmitted:(_)=>_send(),decoration:const InputDecoration(hintText:'Напиши сообщение'))),IconButton(onPressed:_send,icon:const Icon(Icons.send))])]))));}
}

class ProfileScreen extends StatefulWidget{const ProfileScreen({super.key});@override State<ProfileScreen> createState()=>_ProfileScreenState();}
class _ProfileScreenState extends State<ProfileScreen>{UserModel? user;bool loading=true;@override void initState(){super.initState();_load();}Future<void> _load()async{try{final u=await Api.me();if(mounted)setState(()=>user=u);}catch(_){}finally{if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext c){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));if(user==null)return Scaffold(appBar:AppBar(title:const Text('Профиль')),body:Center(child:FilledButton(onPressed:()=>_auth(c),child:const Text('Войти'))));final u=user!;return Scaffold(appBar:AppBar(title:const Text('Профиль'),actions:[IconButton(onPressed:()async{await Api.logout();if(mounted)setState(()=>user=null);},icon:const Icon(Icons.logout))]),body:ListView(padding:const EdgeInsets.all(20),children:[Center(child:CircleAvatar(radius:44,backgroundImage:u.photoUrl.isNotEmpty?NetworkImage(u.photoUrl):null,child:u.photoUrl.isEmpty?const Icon(Icons.person,size:44):null)),const SizedBox(height:12),Center(child:Text(u.name,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold))),Center(child:Text([if(u.age!=null)'${u.age} лет',if(u.city.isNotEmpty)u.city].join(' · '))),if(u.bio.isNotEmpty)...[const SizedBox(height:14),Text(u.bio,textAlign:TextAlign.center)],const SizedBox(height:24),FilledButton.icon(onPressed:()=>_editProfile(c),icon:const Icon(Icons.edit),label:const Text('Редактировать профиль')),const SizedBox(height:20),const Text('Создавай события, иди на них и встречай людей. Здесь нет ленты и лайков — только реальные планы.')]);}Future<void> _editProfile(BuildContext c) async {
  final u=user!;
  final name=TextEditingController(text:u.name);
  final city=TextEditingController(text:u.city);
  final bio=TextEditingController(text:u.bio);
  await showModalBottomSheet(context:c,isScrollControlled:true,showDragHandle:true,builder:(sheet)=>Padding(padding:EdgeInsets.fromLTRB(20,8,20,20+MediaQuery.of(c).viewInsets.bottom),child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
    Text('Редактировать профиль',style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),
    const SizedBox(height:16),
    TextField(controller:name,decoration:const InputDecoration(labelText:'Имя')),
    TextField(controller:city,decoration:const InputDecoration(labelText:'Город')),
    TextField(controller:bio,maxLines:3,decoration:const InputDecoration(labelText:'О себе (необязательно)')),
    const SizedBox(height:18),
    SizedBox(width:double.infinity,child:FilledButton(onPressed:()async{try{final updated=await Api.updateMe(name:name.text.trim(),city:city.text.trim(),bio:bio.text.trim());if(mounted)setState(()=>user=updated);if(sheet.mounted)Navigator.pop(sheet);}catch(e){if(sheet.mounted)ScaffoldMessenger.of(sheet).showSnackBar(SnackBar(content:Text(e.toString())));}},child:const Text('СОХРАНИТЬ'))),
  ]))));
}
void _auth(BuildContext c)=>showModalBottomSheet(context:c,showDragHandle:true,builder:(sheet)=>Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Вход',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:12),const Text('Для первого теста доступны временные dev-кнопки. Google и ВКонтакте подключим отдельным шагом.'),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton(onPressed:()async{await Api.devLogin(id:'demo_user',name:'Новый пользователь');if(sheet.mounted)Navigator.pop(sheet);if(mounted)_load();},child:const Text('Продолжить как новый пользователь'))),const SizedBox(height:8),SizedBox(width:double.infinity,child:OutlinedButton(onPressed:()async{await Api.devLogin(id:'demo_stas',name:'Стас');if(sheet.mounted)Navigator.pop(sheet);if(mounted)_load();},child:const Text('Тестовый вход: Стас')))]));}
